title: CPFA(Climate Prediction For All)
email: 
  - woobin723@gmail.com
  - jjang@gmail.com


baseurl: "/CPFA"
url: "https://hyeok719.github.io"
github_username: hyeok719

# Build settings
remote_theme: jekyll-theme-cayman

nav:
  - name: "Home"
    link: "/"
  - name: "Features"
    link: "/features"
  - name: "Community"
    link: "/community"
  - name: "Contact"
    link: "/contact"

defaults:
  home:
    heading: 'CPFA: Climate Prediction For All'
    subheading: 'An Open-Source Guide for Easy Climate Prediction and Visualization for Non-Experts'
