title: CPFA(Climate Prediction For All)
email: 
  - woobin723@gmail.com
  - jjang@gmail.com


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  woobin723-cmd

# Build settings
theme: jekyll-theme-yat

header_pages:
  - index.md
  - features.md
  - community.md
  - contact.md

defaults:
  home:
    heading: 'CPFA: Climate Prediction For All'
    subheading: 'An Open-Source Guide for Easy Climate Prediction and Visualization for Non-Experts'